# Generated by Django 4.1.13 on 2025-06-04 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clientuser',
            unique_together={('client', 'user')},
        ),
        migrations.RemoveField(
            model_name='clientuser',
            name='is_admin',
        ),
    ]
