# Generated by Django 4.2.12 on 2025-05-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_amount_user_contact_number_user_order_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="amount",
            new_name="ammount",
        ),
    ]
