# Generated by Django 4.2.12 on 2025-05-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="full_name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Super Admin", "Super Admin"),
                    ("Admin", "Admin"),
                    ("User", "User"),
                ],
                max_length=20,
            ),
        ),
    ]
