# Generated by Django 4.2.12 on 2025-05-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_rename_name_user_full_name_remove_user_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")],
                default="user",
                max_length=20,
            ),
        ),
    ]
