# Generated by Django 4.2.12 on 2025-04-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estore", "0002_remove_product_description_product_sku_product_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="SKU",
            field=models.CharField(default="DEFAULT-SKU", max_length=100, unique=True),
        ),
    ]
