# Generated by Django 4.2.12 on 2025-05-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estore", "0003_brand_inventory_subcategory_remove_cart_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(),
        ),
    ]
