# Generated by Django 4.2.12 on 2025-05-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estore", "0004_category_created_at_category_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("orders", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                        default="Ativo",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
