# Generated by Django 4.2.12 on 2025-05-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estore", "0004_alter_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="sub_categories",
        ),
        migrations.AddField(
            model_name="category",
            name="sub_categories",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="categories",
                to="estore.subcategory",
            ),
        ),
    ]
