# Generated by Django 4.2.12 on 2025-05-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("estore", "0005_remove_category_sub_categories_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_gallery",
        ),
        migrations.CreateModel(
            name="ProductGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product_gallery/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="estore.product",
                    ),
                ),
            ],
        ),
    ]
