# Generated by Django 4.1.13 on 2025-06-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('position', models.CharField(choices=[('slider', 'Slider'), ('top_1', 'Banner Top 1'), ('top_2', 'Banner Top 2'), ('home_1', 'Banner Home 1'), ('home_2', 'Banner Home 2')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
