# Generated by Django 4.1.13 on 2025-06-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('slider_1', 'Slider 1'), ('slider_2', 'Slider 2'), ('slider_3', 'Slider 3'), ('top_1', 'Banner Top 1'), ('top_2', 'Banner Top 2'), ('home_1', 'Banner Home 1'), ('home_2', 'Banner Home 2'), ('home_3', 'Banner Home 3'), ('footer_1', 'Banner Footer 1'), ('footer_2', 'Banner Footer 2')], max_length=20),
        ),
    ]
