name: Deploy to cPanel

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This trigger allows you to manually start the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/mcm_backend
            git pull origin main
            chmod +x deploy.sh
            ./deploy.sh
